### List resources
POST {{host}}/api/resources
Accept: application/json
Content-Type: application/json

{
  "url": "https://secutils.dev",
  "delay": 2000,
  "scripts": {
    "resourceFilterMap": "return resource;"
  }
}
